### ISSUE TITLE
可以加个长按手势回调的代理

### ISSUE THREAD

**Issue by lancelot9527** [wangjiegit/WJMoviePlayer#1]
RT，用于保存视频之类的

**Comment by wangjiegit** [comment]
兄弟 可以自己加  我已经懒得整了 没什么用 



        WJMoviePlayerView *playerView = [[WJMoviePlayerView alloc] init];

        playerView.movieURL = self.video_url;

        playerView.coverView = cell.imageView;

        UILongPressGestureRecognizer *lpg = [[UILongPressGestureRecognizer alloc] initWithTarget:self action:@selector(longPressVideoAction:)];

        [playerView addGestureRecognizer:lpg];

 

        [playerView show];








- (void)longPressVideoAction:(UILongPressGestureRecognizer *)lpg {
 
    if (lpg.state != UIGestureRecognizerStateBegan) return;
 
    WJMoviePlayerView *playerView = (WJMoviePlayerView *)lpg.view;
 
    .....
 
}



------------------ 原始邮件 ------------------
发件人: "X xf"<notifications@github.com>;
发送时间: 2019年8月9日(星期五) 中午1:52
收件人: "wangjiegit/WJMoviePlayer"<WJMoviePlayer@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [wangjiegit/WJMoviePlayer] 可以加个长按手势回调的代理 (#1)




Closed #1.
