### ISSUE TITLE
下载完后不播放

### ISSUE THREAD

**Issue by xiedeacc** [wangjiegit/WJMoviePlayer#2]
rt

**Comment by wangjiegit** [comment]
视频url是什么------------------ 原始邮件 ------------------
发件人: "xiedeacc"<notifications@github.com>
发送时间: 2019年11月27日(星期三) 中午12:33
收件人: "wangjiegit/WJMoviePlayer"<WJMoviePlayer@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [wangjiegit/WJMoviePlayer] 下载完后不播放 (#2)



rt
 
&mdash;

**Comment by wangjiegit** [comment]
demo里的视频地址失效了  你试一下其他地址吧
pod 'WJMoviePlayer', '~> 0.0.3'

**Comment by xiedeacc** [comment]
好的谢谢

**Comment by wangjiegit** [comment]
demo里面的视频url无效了 你可以换几个有效的url地址

发自我的iPhone
